Add platform OS patching context to app maintenance page
cloud-gov/cg-site pull request #1177
Opened 2018-01-04 19:57 UTC by brittag

This adds reference information for users who are interested in (or concerned about) how and when we patch underlying platform components. This includes cross-references to the SSP for more details.

Based on draft in [this doc](https://docs.google.com/document/d/1d2LR3hwIbYh6rY4jSXbHZea6cuaU48Q22oodsGWlXok/edit#).

2018-01-04 20:22 UTC, mogul requested changes
This is probably close, but we might want to move it to another page where we can also elaborate on the fact that buildpack updates (and therefore language stack fixes) happen faster.

2018-01-04 20:22 UTC, mogul commented on content/docs/getting-started/app-maintenance.md
> +The cloud.gov platform team is responsible for maintenance and patching of the operating system (Ubuntu) and other platform components. Your applications benefit from these updates automatically.
I wouldn't explicitly name Ubuntu here. CF supports other distros and we'll definitely have Windows cells in future. The vast majority of applications installed with a buildpack don't even care what the distro is.

2018-01-04 20:22 UTC, mogul commented on content/docs/getting-started/app-maintenance.md
> +1. The Ubuntu team releases an update.
Again, change this to something more generic, eg "the upstream OS team releases an update"

2018-01-04 20:22 UTC, mogul commented on content/docs/getting-started/app-maintenance.md
> +1. The [Cloud Foundry BOSH](http://bosh.cloudfoundry.org/) team packages the Ubuntu update into a [“stemcell” image](https://bosh.cloudfoundry.org/docs/stemcell.html) and releases the stemcell update
s/Ubuntu/OS/

2018-01-04 20:23 UTC, jmcarp commented on content/docs/getting-started/app-maintenance.md
> +1. The cloud.gov system picks up the stemcell update, checks it with tests, and deploys the update to production.
Nit: we could be a little more specific about tests here. What about something like "The cloud.gov system picks up the stemcell update, deploys the new stemcell to our staging environment, and verifies that all components are operating as expected before deploying to production."?

2018-01-04 20:23 UTC, jmcarp commented on content/docs/getting-started/app-maintenance.md
> +1. The [Cloud Foundry BOSH](http://bosh.cloudfoundry.org/) team packages the Ubuntu update into a [“stemcell” image](https://bosh.cloudfoundry.org/docs/stemcell.html) and releases the stemcell update
Tiny nit/opinion: smart quotes are bad.

2018-01-05 01:35 UTC, brittag commented
@mogul Updated to remove the specific operating system name! There may generally be some value in naming the OS/distribution for people concerned about patch frequency, but it's not important for a general overview.

@jmcarp I added detail for the test process + removed the smart quotes. :D

2018-01-05 02:33 UTC, mogul requested changes

2018-01-05 02:33 UTC, mogul commented on content/docs/getting-started/app-maintenance.md
> +1. When the production deployment is complete (typically within 24-48 hours), the platform automatically restarts your applications.
How about "As part of the production deployment (typically within 24-48 hours), the platform automatically restarts your application instances on a host running the updated operating system."

2018-01-05 03:23 UTC, mogul submitted a review, later dismissed
Fine to merge if you do this...

2018-01-05 14:34 UTC, pburkholder approved these changes

2018-01-05 14:35 UTC, merged