[Do not merge yet] draft 13.1-13.2 release notes
cloud-gov/cg-site pull request #1205
Opened 2018-02-12 17:17 UTC by femmebot

![screencapture-localhost-1313-updates-2018-02-14-fec-case-study-upcoming-cloud-foundry-summit-and-platform-updates-1518455622664](https://user-images.githubusercontent.com/471514/36109853-954a36b6-0fee-11e8-90b7-7664c2ae8fbf.png)

2018-02-12 22:46 UTC, pburkholder commented on content/updates/2018-02-14-fec-case-study-upcoming-cloud-foundry-summit-and-platform-updates.md
> +- [Upgrade to the latest version of the CF CLI tool](https://github.com/cloudfoundry/cli/releases) for improvements and bug fixes.
>The latest release was v6.34.1 on January 17.

2018-02-12 23:00 UTC, pburkholder reviewed
I like the changes you've made here; it's useful to have some highlights from the buildpack updates.

I've made one comment about, perhaps, adding the last CLI version and release date.

I think we should switch the sections for `Platform releases` and `Buildpack updates`. The buildpacks are customer facing, but customers should never see any impact from platform updates, so let's move those platform updates below the buildpack updates.

2018-02-13 03:55 UTC, mogul commented
I agree with Peter's suggestion on the order. Beyond that I'm 👍 on this one.

2018-02-13 03:55 UTC, mogul requested changes
Change ordering of platform vs buildpack updates.

2018-02-13 18:05 UTC, brittag commented
I can't run it locally right now but the preview here looks great! Suggest putting Elasticsearch 5.6 in the title instead of the FEC case study, since we previously talked about the (older) version of the case study in release notes but 5.6 is brand-new. But just a suggestion - @femmebot up to you!

2018-02-13 19:32 UTC, mogul approved these changes

2018-02-13 19:33 UTC, mogul requested changes
(Doh, still want the order reversed between Buildpack and Platform updates.)

2018-02-13 19:33 UTC, mogul submitted a review, later dismissed
(Never mind, I can't read.)

2018-02-13 19:33 UTC, mogul commented
:shipit:

2018-02-13 22:34 UTC, brittag approved these changes

2018-02-13 23:15 UTC, merged