Copy cdn broker custom headers docs from broker repo.
cloud-gov/cg-site pull request #1251
Opened 2018-04-14 02:13 UTC by jmcarp

h/t @cmc333333

2018-04-15 17:59 UTC, mogul requested changes

2018-04-15 17:59 UTC, mogul commented on content/docs/services/cdn-route.md
> +CloudFront can forward up to 10 custom headers. Because this broker automatically forwards the `Host` header when not using a [custom origin](#custom-origins), you can whitelist up to nin headers by
s/nin/nine/

2018-04-16 17:36 UTC, brittag commented on content/docs/services/cdn-route.md
> -Other headers, such as HTTP auth, are stripped by default.
Is it still true that HTTP auth headers are stripped by default? If so, that one still seems like a good one to call out specifically, since it can mean that people's sites are unexpectedly missing Basic Auth that they intended to have (if I'm understanding this correctly).

2018-07-25 19:28 UTC, brittag commented on content/docs/services/cdn-route.md
> -Other headers, such as HTTP auth, are stripped by default.
@jmcarp This PR still seems really useful to me - would you be up for taking another look at clarifying this bit of it? It might not be necessary, I'm just not sure.

2019-07-08 01:26 UTC, mogul approved these changes

2019-07-08 01:33 UTC, merged