Remove packages and rates page to reduce redundancy in pricing content
cloud-gov/cg-site pull request #1307
Opened 2018-07-27 18:58 UTC by jenniferthibault

**Summary:**

This removes the [Packages and rates page](https://cloud.gov/overview/pricing/rates/) from the documentation site, and updates all content formerly pointing to it to the main [Pricing page](https://cloud.gov/pricing/), making it the canonical source. 

We're removing this page because the content is mostly duplicative. If any content is removed in this process that isn't redundant, we expect to hear customers asking for it, and will then reinstate it in a more integrated and less-redundant place. 

Addresses https://cm-jira.usa.gov/browse/CG-778

**Reviewing questions**
When replacing links, I chose to avoid updating links in published Release notes documents, which appear in these three instances. Does this keep with the team's norms?
- `content/updates/2017-02-02-fedramp-authorized.md`
- `content/updates/2017-05-22-release-notes.md`
- `content/updates/2017-12-08-starting-now-sandboxes-expire-after-90-days.md`

Feedback especially welcome.

2018-07-27 19:24 UTC, mogul requested changes
Going to investigate what tests are failing, but let's get started with this.

2018-07-27 19:24 UTC, mogul commented on content/overview/pricing/rates.md
> -aliases:
I'd like to see an `aliases` stanza similar to this one added to the front-matter of `/content/pricing/_index.md`. (In fact it looks like you can just move this one over there, since it includes a reference to where this page used to be.) That will ensure that anyone visiting the now-vacant URL will see the main pricing page instead.

2018-07-27 19:29 UTC, mogul commented
The build is breaking because these links to the now-missing page still exist:

> Building sites … ERROR 2018/07/27 12:25:59 error processing shortcode 
> "_internal/shortcodes/relref.html" for page "updates/2017-12-08-starting-now-sandboxes-expire-after-90-days.md": template: _internal/shortcodes/relref.html:1:76: executing "_internal/shortcodes/relref.html" at <relref .Page (.Get 0...>: error calling relref: No page found with path or logical name "overview/pricing/rates.md".
> ERROR 2018/07/27 12:25:59 error processing shortcode "_internal/shortcodes/relref.html" for page "updates/2017-05-22-release-notes.md": template: _internal/shortcodes/relref.html:1:76: executing "_internal/shortcodes/relref.html" at <relref .Page (.Get 0...>: error calling relref: No page found with path or logical name "overview/pricing/rates.md".
> ERROR 2018/07/27 12:25:59 error processing shortcode "_internal/shortcodes/relref.html" for page "updates/2017-02-02-fedramp-authorized.md": template: _internal/shortcodes/relref.html:1:76: executing "_internal/shortcodes/relref.html" at <relref .Page (.Get 0...>: error calling relref: No page found with path or logical name "overview/pricing/rates.md".
> Total in 1281 ms
> Error: Error building site: logged 3 error(s)

In answer to your question:
> When replacing links, I chose to avoid updating links in published Release notes documents, which appear in these three instances. Does this keep with the team's norms?

Yes, that's the right thing to do. We ensure stale links of that type (and links in users' bookmarks) do not become broken links by adding aliases for the removed page to an alternative page.

So, in this case, adding that `aliases` stanza on `/content/pricing/_index.md` should resolve the build errors too!

2018-07-27 20:40 UTC, jenniferthibault commented
Thanks @mogul — that is a super helpful explainer on what the alias section is for.  I copied over that alias content from the former page but it didn't seem to fix the build. Any ideas?

2018-07-30 17:35 UTC, jenniferthibault commented on content/overview/pricing/rates.md
> -aliases:
Added 👍

2018-07-30 17:37 UTC, jenniferthibault commented
Adding aliases didn't resolve the builds, so instead I updated the old release notes to either remove links to pages that no longer exist, or point to the most updated source of the information on a case-by-case basis depending on the context of the content.

This fixed the builds and the tests are passing 🎉 . Back to you @mogul !

2018-07-30 17:41 UTC, mogul approved these changes

2018-07-30 17:41 UTC, merged