added ipv6 clarification.
cloud-gov/cg-site pull request #1417
Opened 2019-04-05 16:17 UTC by mxplusb

made things a bit more clear.

Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>

//cc @bengerman13

2019-04-05 16:23 UTC, bengerman13 submitted a review, later dismissed
:shipit:

2019-04-05 16:24 UTC, mogul approved these changes

2019-04-05 16:24 UTC, mogul commented
@pburkholder FYI... Suggest changes if you think this isn't clear enough.

2019-04-05 16:25 UTC, mxplusb commented
//cc @pburkholder

2019-04-05 16:26 UTC, mogul commented on content/docs/compliance/domain-standards.md
> +cloud.gov has basic support for IPv6. cloud.gov supports two types of application access, external and internal. External access is when traffic reaches an application from outside the cloud.gov plat
Should probably clean up "but not for internal access, only IPv4 is supported" to "but for internal access, only IPv4 is supported" to remove ambiguity.

2019-04-05 16:28 UTC, mogul commented on content/docs/compliance/domain-standards.md
> +cloud.gov has basic support for IPv6. cloud.gov supports two types of application access, external and internal. External access is when traffic reaches an application from outside the cloud.gov plat
(Sorry, shoulda put that in a review and requested changes.)

2019-04-05 16:28 UTC, mogul requested changes
Just reopening to make sure the point above gets addressed.

2019-04-08 00:27 UTC, mogul approved these changes

2019-04-08 00:45 UTC, merged