Adds dev env setup guide
cloud-gov/cg-site pull request #1491
Opened 2019-10-17 12:47 UTC by hillaryj

Adds a local development environment setup guide for GSA issued mac assets. Also renames the Virtaul Box instructions to reduce confusion.

2019-10-17 16:01 UTC, siennathesane requested changes

2019-10-17 16:01 UTC, siennathesane commented on content/docs/ops/creating-a-local-dev-environment-in-Virtual-Box.md
> +Note: This process is no longer used by the cloud.gov platform operations team but are left in place for reference.
I would just rip this out and replace it with `cf dev`. Same thing, for most intents and purposes.

2019-11-06 17:29 UTC, bengerman13 approved these changes

2019-11-06 18:07 UTC, siennathesane approved these changes

2019-11-06 18:07 UTC, merged