Update services listing for SQL Server
cloud-gov/cg-site pull request #1615
Opened 2020-04-14 12:53 UTC by mheadd

## Changes proposed in this pull request:
- Updates the [services listing](https://cloud.gov/docs/overview/portfolio-analysis/) to indicate that support for SQL Server is at a future date TBD.
- Fixes #1611  

## security considerations
None. Content change only

2020-04-22 21:40 UTC, eddietejeda requested changes

2020-04-22 21:40 UTC, eddietejeda commented on _docs/overview/portfolio-analysis.md
> +  - SQL Server (potentially available at a future date TBD)
Lets remove all references on the website about potential work or services.

2020-04-22 22:22 UTC, mheadd commented
Preview link for the page that was changed is [here](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/update-rds-list/docs/overview/portfolio-analysis/).

2020-04-24 14:47 UTC, eddietejeda approved these changes

2020-04-24 14:51 UTC, eddietejeda approved these changes

2020-04-24 14:58 UTC, merged