Add support package page
cloud-gov/cg-site pull request #1762
Opened 2020-08-29 00:09 UTC by apburnes

## Changes proposed in this pull request:
- Add support package page
- Add support package data with info about package description, price, and hours
- Add link under the pricing tab on the header

:sunglasses:[PREVIEW URL](https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.app.cloud.gov/preview/cloud-gov/cg-site/support-package-page/support-packages/)

## Security Considerations
None

2020-09-01 20:43 UTC, eddietejeda requested changes
For FAQ, we should make the language more accessible. Here are some changes I recommend, but please check with the team first.



What happens to the money that is not used within the fiscal year or period of performance?
Any money that is not used will be returned to the agency through the "deobligation" process.
    
    
If an agency does not use all the allocated support hours, would they be able to reduce paid support hours for future years?
Yes, we see support hours as a good way for an agency to get started with the platform. Once your team is comfortable with the platform, you should reduce the number of paid support hours.


Is there a way to roll over unused hours to the next fiscal year?
Yes, it's possible. But that depends on the agency's authority and funds. For example, some money can cross fiscal year ("no-year money") while other funds must be used within a set time frame ("3-year money").


What are the limits of the paid support packages?
We will not do direct development on the agency's application. We will only help, analyze, and assist.

2020-09-04 20:19 UTC, ccostino reviewed
Thanks, @apburnes!  I noticed one formatting thing and made a suggestion on the last Q&A, if it helps at all.

2020-09-04 20:19 UTC, ccostino commented on _pages/support-packages.md
> +                  <p class="font-body-md">Yes, unspent monies need to be deobligated.</p>
For some reason there is an extra blank line being rendered above this answer; the other answers don't have the extra space.  I'm not sure why, though!

2020-09-04 20:19 UTC, ccostino commented on _pages/support-packages.md
> +                    We will not do direct development on the agency's application. We will only help, analyze, and assist.
Is this fair to say instead to help clarify this more?

```suggestion
                    We will not perform direct development on the agency's application. We will only help, analyze, and assist with improving application performance and stability on the platform.
```

2020-09-16 13:08 UTC, eddietejeda approved these changes

2020-09-16 13:17 UTC, merged