Replacing Federalist with cloud.gov Pages
cloud-gov/cg-site pull request #2202
Opened 2022-11-08 15:00 UTC by hursey013

## Changes proposed in this pull request:
- Simple text swaps (Federalist -> cloud.gov Pages) where appropriate
- Update support email and slack channels
- Unpublished the "How pages works" page
- Updated netlify cms config/docs to reflect new url

## Security Considerations
None

2022-11-08 16:51 UTC, drewbo requested changes
One small change inline and other notes here. Not sure if we want to break any of these out into separate PRs but let me know if you want me to jump on any of these:

### Need new screenshots
- [x] /pages/documentation/
- [x] /pages/documentation/getting-started-with-jekyll/
- [ ] /pages/documentation/instructional-demos/
- [x] /pages/documentation/previews/
- [x] /pages/documentation/customization/#pages-default-404-page
- [x] /pages/documentation/env-vars-on-pages-builds/

### Broken links
- [ ] /pages/documentation/custom-headers/#examples
- [ ] /pages/documentation/how-pages-works/
   - This page also needs link/text updates throughout

### Other
- [ ] Update /pages/documentation/access-permissions/#personal-access for getting Pages access
- [ ] Migrate mono repo example at /pages/documentation/monorepos-on-pages/
- [x] Switch to `npm run pages` in examples
- [x] Update templates at `_data/pages/templates.yml` (not positive where they are used)

2022-11-08 16:51 UTC, drewbo commented on _pages/pages/documentation/supported-site-engines.md
> +To see the exact configuration of the build environment, see the [build environment `Dockerfile`](https://github.com/cloud-gov/pages-garden-build/blob/main/Dockerfile).
`pages-build-container`

2022-11-09 18:22 UTC, hursey013 commented
Appreciate the feedback @drewbo! Couple of notes:

# Need new screenshots
- /pages/documentation/instructional-demos/ - I think it would be great to update these videos, but in the meantime I think keeping the older Federalist videos around is ok, thoughts?

# Broken links
- /pages/documentation/custom-headers/#examples seems to be working for me?
- /pages/documentation/how-pages-works/ - I actually unpublished this because it seemed overly technical for our audience. If we want to keep that page, I can open a separate issue because a significant amount of updates

# Other
- Update /pages/documentation/access-permissions/#personal-access for getting Pages access. Updated this page to reflect the current state of auth/orgs
-  Migrate mono repo example at /pages/documentation/monorepos-on-pages/ - requested access so we can move this to `cloud-gov`

2022-11-09 19:04 UTC, drewbo commented
Looks great @hursey013 
- Agree with waiting on updating the videos
- I didn't specify correctly but the broken link at `/pages/documentation/custom-headers/#examples` is the site linked right below (https://github.com/18F/federalist-uswds-gatsby2/blob/main/federalist.json)
- Let's open a separate issue to chat about the "how it works" page but agree with unpublishing for now
- 👍 on the last two

I think the only remaining change is to find a custom header example to use underneath /pages/documentation/custom-headers/#examples or removing for now

2022-11-09 19:39 UTC, drewbo approved these changes

2022-11-09 19:54 UTC, merged