WIP Add Single-Page-Application Pages KB Article (Review)
cloud-gov/cg-site pull request #2428
Opened 2023-11-02 17:29 UTC by Ephraim-G

## Changes proposed in this pull request:
- Add a Pages specific knowledge base article 
- Add an image to `_assets` folder

## Security Considerations
N/A

2023-11-02 17:41 UTC, svenaas submitted a review, later dismissed
Added a few copyediting suggestions

2023-11-02 17:41 UTC, svenaas commented on _kbarticlespages/single-page-application.md
> +cloud.gov Pages hosts static sites, but this doesn’t mean that developers are limited to only using [“static site generators”](https://jamstack.org/generators/): anything that can be compiled down in
```suggestion
cloud.gov Pages hosts static sites, but this doesn’t mean that developers are limited to only using [“static site generators”](https://jamstack.org/generators/): anything that can be compiled down into HTML can be run on Pages. You can use a single-page application framework like Vue.js, Svelte, Angular, React, etc. and host it seamlessly on the Pages platform. This is achieved via the `npm run pages` command which allows developers to add a custom build script, and we’ll automatically publish everything in the `_site` folder. Details on utilizing a custom build script will be covered later in the article.  
```

2023-11-02 17:41 UTC, svenaas commented on _kbarticlespages/single-page-application.md
> +In this example we will be taking a look at a simple single-page application which uses the React library and React Router v6. You can view a repository with a full example here <https://github.com/E
```suggestion
In this example we will be taking a look at a simple single-page application which uses the React library and React Router v6. You can view a repository with a full example here <https://github.com/Ephraim-G/react_spa4> and see the results in Pages [here](https://federalist-01aa8660-8aca-452d-a270-5e58ffa18645.sites.pages.cloud.gov/site/ephraim-g/react_spa4/). There are also more detailed instructions on how to run this locally in the repositories’ README.md. This article serves as a high level overview and will highlight three key features:
```

2023-11-02 17:41 UTC, svenaas commented on _kbarticlespages/single-page-application.md
> +Static site generators like Jekyll and Hugo handle routing by creating an HTML file at each path that can be requested by the user. For single-page applications, we will only render one HTML file: in
```suggestion
Static site generators like Jekyll and Hugo handle routing by creating an HTML file at each path that can be requested by the user. For single-page applications, we will only render one HTML file: index.html, which loads the JavaScript necessary for running our application and router.
```

2023-11-02 17:41 UTC, svenaas commented on _kbarticlespages/single-page-application.md
> +All of the routing is located in the `index.js` file. Here we import all our components, css and functions. We create the `<BrowserRouter>` and use the `<RouterProvider>` to provide that router to ou
```suggestion
All of the routing is located in the `index.js` file. Here we import all our components, CSS and functions. We create the `<BrowserRouter>` and use the `<RouterProvider>` to provide that router to our application. The parent route registers a `Layout` component which essentially wraps all the other page components thus providing a uniform structure/design for all the components.
```

2023-11-02 18:19 UTC, Ephraim-G commented
Thank you @svenaas

2023-11-08 16:25 UTC, drewbo requested changes
Few small header changes, otherwise good to go

2023-11-08 16:25 UTC, drewbo commented on _kbarticlespages/single-page-application.md
> +## Intro
```suggestion
```

2023-11-08 16:25 UTC, drewbo commented on _kbarticlespages/single-page-application.md
> +## Intro
Removing this so the first lines render as a preview in the list: https://cg-88d42ca6-59d7-47e0-9500-4dd9251360b9.sites.pages.cloud.gov/preview/cloud-gov/cg-site/KB/pages/knowledge-base/

2023-11-08 16:25 UTC, drewbo commented on _kbarticlespages/single-page-application.md
> +## Key features of a single-page application on Pages
```suggestion
```

2023-11-08 16:25 UTC, drewbo commented on _kbarticlespages/single-page-application.md
> +#### Application Routing
```suggestion
## Application Routing
```

2023-11-08 16:25 UTC, drewbo commented on _kbarticlespages/single-page-application.md
> +#### Application Routing
Makes all the sections the same weight

2023-11-08 17:09 UTC, apburnes reviewed
Thanks for putting this info together! I've got a couple of comments.

2023-11-08 17:09 UTC, apburnes commented on _kbarticlespages/single-page-application.md
> +  You can see how this is included in the build command in the [repository](https://github.com/Ephraim-G/react_spa4/blob/main/build.sh#L3C32-L3C32).
You've got a `postbuild.sh` in the pages build script in package.json that does not exist and fails the build. https://github.com/Ephraim-G/react_spa4/blob/main/package.json#L21

2023-11-08 17:09 UTC, apburnes commented on _kbarticlespages/single-page-application.md
> +In this example we will be taking a look at a simple single-page application which uses the React library and React Router v6. You can view a repository with a full example here <https://github.com/E
We should probably remove this from your personal repository into a Pages examples repository in cloud.gov.

2023-11-08 18:19 UTC, Ephraim-G commented on _kbarticlespages/single-page-application.md
> +  You can see how this is included in the build command in the [repository](https://github.com/Ephraim-G/react_spa4/blob/main/build.sh#L3C32-L3C32).
nice catch, since we're not doing anything with the custom 404 page I removed that script but missed that in the package.json.

2023-11-08 20:36 UTC, Ephraim-G commented
@apburnes ready for final approval

2023-11-08 21:21 UTC, apburnes commented on _kbarticlespages/single-page-application.md
> +In this example we will be taking a look at a simple single-page application which uses the React library and React Router v6. You can view a repository with a full example here <https://github.com/E
```suggestion
In this example we will be taking a look at a simple single-page application which uses the React library and React Router v6. You can view a repository with a full example here <https://github.com/cloud-gov/pages-example-ssp> and see the results in Pages [here](https://federalist-01aa8660-8aca-452d-a270-5e58ffa18645.sites.pages.cloud.gov/site/ephraim-g/react_spa4/). There are also more detailed instructions on how to run this locally in the repositories’ README.md. This article serves as a high level overview and will highlight three key features:
```

2023-11-08 21:22 UTC, apburnes commented on _kbarticlespages/single-page-application.md
> +  You can see how this is included in the build command in the [repository](https://github.com/Ephraim-G/react_spa4/blob/main/build.sh#L3C32-L3C32).
```suggestion
  You can see how this is included in the build command in the [repository](https://github.com/cloud-gov/pages-example-spa/blob/main/build.sh#L3C32-L3C32). 
```

2023-11-09 16:44 UTC, drewbo approved these changes

2023-11-09 16:45 UTC, merged