Add table listing trade-offs
cloud-gov/cg-site pull request #434
Opened 2016-09-28 20:37 UTC by mogul

Be a little more explicit here.
Ref https://twitter.com/benbravo73/status/781125385777999872

2016-09-29 04:13 UTC, afeld requested changes

2016-09-29 04:13 UTC, afeld commented on content/apps/experimental/docker.md
> +| Cons | Difficult to recreate the execution environment locally<br \>Testing compilation and the result of staging is harder | Added responsibility for all security updates and bug fixes<br \>More c
Mind citing the tweet/author/deck here?

2016-10-01 19:57 UTC, mogul commented on content/apps/experimental/docker.md
> +| Cons | Difficult to recreate the execution environment locally<br \>Testing compilation and the result of staging is harder | Added responsibility for all security updates and bug fixes<br \>More c
No, but I don't know how best to do it. Is there a norm?

2016-10-02 18:26 UTC, afeld commented on content/apps/experimental/docker.md
> +| Cons | Difficult to recreate the execution environment locally<br \>Testing compilation and the result of staging is harder | Added responsibility for all security updates and bug fixes<br \>More c
I'd say "table inspired by such-and-such" or "more information" in italics below the table like a caption, or you could even put it in an HTML comment if you didn't want it to distract readers.

2016-10-02 23:49 UTC, mogul commented on content/apps/experimental/docker.md
> +| Cons | Difficult to recreate the execution environment locally<br \>Testing compilation and the result of staging is harder | Added responsibility for all security updates and bug fixes<br \>More c
The context was pretty free of additional context; it was a photo of a slide being shown on stage at the CF Summit in Europe this week. I'll put it in as an HTML comment.

2016-10-02 23:55 UTC, mogul commented
(It's unclear how to explicitly indicate that I addressed the requested feedback and ask for verification.)

2016-10-03 00:18 UTC, merged