suggest setting up continuous integration before continuous deployment
cloud-gov/cg-site pull request #701
Opened 2017-01-07 21:42 UTC by afeld

/cc @rdgsa

2017-01-10 16:26 UTC, LinuxBozo requested changes

2017-01-10 16:26 UTC, LinuxBozo commented on content/docs/apps/continuous-deployment.md
> +1. The [Production Ready Guide]({{< relref "production-ready.md" >}})
I would reverse the order of those.. Production Ready gets you ready for CI, by pointing out using a manifest, etc.

2017-01-10 16:31 UTC, afeld commented on content/docs/apps/continuous-deployment.md
> +1. The [Production Ready Guide]({{< relref "production-ready.md" >}})
Makes total sense! Updated.

2017-01-10 16:31 UTC, LinuxBozo approved these changes

2017-01-13 18:42 UTC, brittag commented
@LinuxBozo @afeld I adjusted this intro to give a bit more context - does it still look right? I especially wanted to narrow the reference to the production-ready guide to avoid a loop, since one of the production-ready guide recommendations is to use continuous deployment. :)

![screen shot 2017-01-13 at 10 40 30 am](https://cloud.githubusercontent.com/assets/391313/21941268/c6353c5c-d97c-11e6-9d3a-be7f3344fa62.png)

2017-01-14 00:51 UTC, afeld commented on content/docs/apps/continuous-deployment.md
> +On GovCloud: use `api: https://api.fr.cloud.gov`
I would suggest we use our environment blocks, for consistency.

2017-01-14 00:52 UTC, afeld commented
Just the one thing - good for me otherwise!

2017-01-14 01:36 UTC, brittag commented on content/docs/apps/continuous-deployment.md
> +On GovCloud: use `api: https://api.fr.cloud.gov`
Done! Also added info about this for the other suggested services.

2017-01-17 14:31 UTC, merged