[WIP - don't merge] Update GovCloud migration process info for outside-TTS use
cloud-gov/cg-site pull request #769
Opened 2017-02-15 02:43 UTC by brittag

**Don't merge yet.** This needs to be updated with the upcoming link to self-invitation for GovCloud access.

These changes are meant to help non-18F people migrate their orgs to GovCloud, to support [this message](https://docs.google.com/document/d/1l-akEeE2cRxML_svuQTmo__naN80sN-Jj_n6Jqt9DoE/edit#heading=h.jgcxtjglazl) and related messaging.

Changes:

* Start with getting access to GovCloud.
* Provide alternative to org request form for people outside TTS.
* Remove links to incomplete info about service migration.
* Remove "unresolved details" chunk.

2017-02-15 17:59 UTC, brittag commented
(To be clear about the WIP-ness of this - I don't currently have plans to work on this more - would like to hand it to migrators for finishing it up. :) )

2017-02-15 21:19 UTC, brittag commented
This depends on https://github.com/18F/cg-uaa-extras/pull/81 for the link to self-invitation.

2017-02-16 01:32 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * For everyone else, one of your org managers should email [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov) to request the creation of your org in GovCloud. Include the name of your
Should they also specify the quota they'd like, or does the self-invitation process include that?

2017-02-16 17:40 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * For everyone else, one of your org managers should email [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov) to request the creation of your org in GovCloud. Include the name of your
@jcscottiii @rememberlenny [Self-invitation](https://account.fr.cloud.gov/signup) is now a thing (:tada:)... is requesting a creation of an org still a manual process that requires them to email us the org name and desired quota, though? Asking so I can update this step.

2017-02-16 17:53 UTC, fureigh requested changes
I think this is good to go, pending confirmation that the flagged non-18F/TTS instructions are accurate.

2017-02-16 17:53 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * If you are in 18F/TTS at GSA, fill out the [organization request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1). Sp
@jcscottiii @rememberlenny Are these non-18F/TTS instructions accurate?

2017-02-16 17:54 UTC, brittag commented on content/docs/apps/govcloud.md
> +    * For everyone else, one of your org managers should email [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov) to request the creation of your org in GovCloud. Include the name of your
Yes, creating an org is still a manual process they should email us about. Self-invitation is unrelated - it's just about access to the GovCloud environment.

2017-02-16 18:04 UTC, jcscottiii commented on content/docs/apps/govcloud.md
> +    * If you are in 18F/TTS at GSA, fill out the [organization request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1). Sp
Would like to make sure they tag their subject line with something like `[GovCloud Org Creation]`

2017-02-16 18:29 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * If you are in 18F/TTS at GSA, fill out the [organization request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1). Sp
@jcscottiii Do we need them to specify a quota too or nah?

2017-02-16 18:45 UTC, jcscottiii commented on content/docs/apps/govcloud.md
> +    * If you are in 18F/TTS at GSA, fill out the [organization request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1). Sp
nahh

2017-02-16 18:46 UTC, jcscottiii commented on content/docs/apps/govcloud.md
> +    * If you are in 18F/TTS at GSA, fill out the [organization request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1). Sp
nahh

2017-02-16 18:46 UTC, jcscottiii approved these changes

2017-02-16 19:17 UTC, mogul commented on content/docs/apps/govcloud.md
> +    * For everyone else, one of your org managers should email [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov?subject=[GovCloud Org Request]) to request the creation of your org in GovC
You can provide a default body for the `mailto:` URL that prompts them for any necessary information as they fill out the mail.

2017-02-16 20:33 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * If you are in 18F/TTS at GSA, fill out the [organization request form](https://docs.google.com/a/gsa.gov/forms/d/e/1FAIpQLSd4HmcGfJW3EBnpewTFDD-urRFPp1LN0DcwNB_FxZgUn8ho9g/viewform?c=0&w=1). Sp
I'll move forward on merging this, but: how/when will we get this info from them? Or do they just get set up with a default?

2017-02-16 20:35 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * For everyone else, one of your org managers should email [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov?subject=[GovCloud Org Request]) to request the creation of your org in GovC
Good call. Seems like there may be further changes to what constitutes the necessary information, so I'll merge this as-is and can start a PR with a minimal version.

2017-02-16 20:36 UTC, fureigh commented on content/docs/apps/govcloud.md
> +    * For everyone else, one of your org managers should email [cloud-gov-support@gsa.gov](mailto:cloud-gov-support@gsa.gov?subject=[GovCloud Org Request]) to request the creation of your org in GovC
...ah, this request is blocking the merge. Commit TK, then.

2017-02-16 20:44 UTC, fureigh approved these changes

2017-02-16 20:45 UTC, merged