[ work in progress ] Document rotation of IAM user access keys
cloud-gov/cg-site pull request #802
Opened 2017-03-01 14:48 UTC by rogeruiz

Part of secret rotation, this documentation covers versioning the access_key and secret_access_key during a secret rotation.

2017-03-01 17:48 UTC, LinuxBozo commented
I have a concern that without proper diff context, all these examples will lose a bit of meaning. Very hard to see from the examples what exactly is going on if you really aren't paying close attention.

2017-03-01 17:50 UTC, rogeruiz commented
Yeah very much agree. Maybe having more generic examples makes more sense? @LinuxBozo 

The `iam_user/base` and `iam_user/rotation` will be two that make sense to include. But if we make the actual modules to update more generic we could even point to this as a start for creating `iam_user` modules. 🤷‍♂️

2017-03-03 23:03 UTC, rogeruiz commented
Noticed some typos. So this isn't ready to merge yet.

2017-03-07 18:29 UTC, rogeruiz commented
This should now be ready to be reviewed. @jmcarp @rememberlenny

2017-03-07 18:34 UTC, cnelson commented on content/docs/ops/rotating-iam-users.md
> +The example above leverages `_v2` as the now current version by removing the
Should this be v2 / v3, not v1/v2 (based on your samples)

2017-03-07 18:34 UTC, cnelson commented on content/docs/ops/rotating-iam-users.md
> +The example above shows keys being rotated from `_v1` to `_v2`. The example
Should this be v2 / v3, not v1/v2 (based on your sample diff)

2017-03-07 19:03 UTC, rogeruiz commented on content/docs/ops/rotating-iam-users.md
> +The example above leverages `_v2` as the now current version by removing the
good catch. thanks.

2017-03-07 19:05 UTC, rogeruiz commented
completely forgot to push up my changes. Should be resolved now @cnelson

2017-03-07 21:13 UTC, cnelson reviewed
LGTM me, but I think @LinuxBozo should approve since he raised the initial issue.  Does this make more sense with the additional context?

2017-03-07 21:24 UTC, rogeruiz commented
True. I just wish we had a syntax highlighter for the diffs. 😢

2017-03-07 22:40 UTC, LinuxBozo requested changes

2017-03-07 22:40 UTC, LinuxBozo commented on content/docs/ops/rotating-iam-users.md
> +-  value = "${aws_iam_access_key.iam_access_key.access_key_id}"
Shouldn't this old value be v2?

2017-03-07 22:40 UTC, LinuxBozo commented on content/docs/ops/rotating-iam-users.md
> +-  value = "${aws_iam_access_key.iam_access_key.secret_access_key}"
This old value should be v2 as well, yeah?

2017-03-08 20:27 UTC, jmcarp approved these changes

2017-03-08 20:27 UTC, LinuxBozo approved these changes

2017-03-08 20:28 UTC, merged