add may 18 release notes
cloud-gov/cg-site pull request #894
Opened 2017-05-18 16:23 UTC by jameshupp

@brittag I’m specifically interested in whether I described the DISA letter correctly.

I also don’t see documentation to link to for the ELB router health check fix, but could link to Amazon on what ELBs are or something else of our own, maybe the GH repo.

2017-05-18 22:22 UTC, mogul requested changes

2017-05-18 22:22 UTC, mogul commented on content/updates/2017-05-18-release-notes.md
> +Elastic Load Balancers (ELBs) now perform router health checks before putting a particular router back in service. Previously, ELBs occasionally produced 502 errors by sending traffic across unhealth
We need to make this more customer-centric; assume they don't know what ELBs or routers are! How about:

> We've improved our process for updating the part of cloud.gov that routes traffic to your application. Previously, you might have seen occasional 502 errors when we made updates.

?

2017-05-18 22:22 UTC, mogul commented on content/updates/2017-05-18-release-notes.md
> +- The Defense Information Systems Agency (DISA) has issued a [provisional authorization for Department of Defense teams]({{< relref "overview/security/fedramp-tracker.md#how-this-p-ato-helps-your-tea
Last mangled sentence is

2017-05-18 22:22 UTC, mogul commented on content/updates/2017-05-18-release-notes.md
> +- The cloud.gov team is looking to make the cloud.gov platform easier to evaluate and use. We’ll ask you a few questions and ask you to walk us through using some aspect of the platform via screensha
I'd add to the end of the first sentence "and we're recruiting volunteers who can help us do that."

There's a discontinuous jump from the first sentence to the second. How about making the order 1-3-2 instead of 1-2-3?

I'd be in favor of putting this right up front, at the very top of the release notes! It's pretty buried here.

2017-05-19 00:59 UTC, brittag commented
@jameshupp Yes, this is a good description of the DISA letter! I put in Bret's suggestions and made a couple other edits to reflect the language that developers tend to use: PHP buildpacks, "Platform releases" instead of "Production releases" (all of the things in the release notes are production releases in some sense), usually "applications" rather than "systems".

2017-05-19 15:25 UTC, jameshupp commented
So these are now May 19 release notes, but I think they're ready to go. @brittag made @mogul's requested changes, and the date is now right.

2017-05-21 19:21 UTC, mogul approved these changes

2017-05-21 19:22 UTC, merged

2017-05-21 19:22 UTC, mogul commented
Merged, but don't forget to send the notification to existing users too!