Clarify Suspicious AWS Events
cloud-gov/cg-site pull request #922
Opened 2017-06-08 16:02 UTC by commit-dkp

Rather than define what is unusual, define what is expected.

2017-06-09 21:17 UTC, rogeruiz requested changes
This looks great. 👍 here's some changes. Also in the future I think it's good to do whitespace changes to the docs, but it made it difficult to review. I'd say either focus on just the changes and whitespace / line break changes for the lines your editing or parts your editing **or** say in the opening comment that it should be viewed in _Rich Diff Mode_.

2017-06-09 21:17 UTC, rogeruiz commented on content/docs/ops/maintenance-list.md
> +personally, you are responsible for ensuring that an appropriate person does it.
Can we mention here that people should reach out at the end of program-level standups in order to get visibility with people who are in the best position to help?

2017-06-09 21:17 UTC, rogeruiz commented on content/docs/ops/maintenance-list.md
> +for each deployment is current.
We're talking about having a pipeline task for this. But it shouldn't stop this update. :+1:

for your eyes, https://gsa-tts.slack.com/archives/C0ENP71UG/p1496895499351167

2017-06-09 21:17 UTC, rogeruiz commented on content/docs/ops/maintenance-list.md
> +indicated cloud.gov operator(s) and if necessary follow the
Can we make `indicated cloud.gov operator(s)` a link to [this Google doc](https://docs.google.com/spreadsheets/d/1mW3tphZ98ExmMxLHPogSpTq8DzYr5Oh8_SHnOTvjRWM/edit#gid=0)?

2017-06-09 21:59 UTC, commit-dkp commented on content/docs/ops/maintenance-list.md
> +personally, you are responsible for ensuring that an appropriate person does it.
Added in https://github.com/18F/cg-site/pull/922/commits/96f57d379f819e0af0564b483d9e5d0c7b18600e .

2017-06-10 02:14 UTC, rogeruiz approved these changes
:shipit:

2017-06-10 02:14 UTC, merged